// Generated by scripts/build-miniprogram-assets.ts — do not edit.
module.exports = {
  "exercise": {
    "ex-goblet-squat": [
      {
        "src": "/assets/characters/exercise/squat-0.svg",
        "motion": null
      },
      {
        "src": "/assets/characters/exercise/squat-1.svg",
        "motion": "sq-legs"
      },
      {
        "src": "/assets/characters/exercise/squat-2.svg",
        "motion": "sq-upper"
      }
    ],
    "ex-dumbbell-row": [
      {
        "src": "/assets/characters/exercise/row-0.svg",
        "motion": null
      },
      {
        "src": "/assets/characters/exercise/row-1.svg",
        "motion": "row-arm"
      }
    ],
    "ex-glute-bridge": [
      {
        "src": "/assets/characters/exercise/bridge-0.svg",
        "motion": null
      },
      {
        "src": "/assets/characters/exercise/bridge-1.svg",
        "motion": "br-hip"
      }
    ],
    "ex-walk": [
      {
        "src": "/assets/characters/exercise/walk-0.svg",
        "motion": "walk-bean"
      },
      {
        "src": "/assets/characters/exercise/walk-1.svg",
        "motion": null
      }
    ]
  },
  "food": {
    "food-egg": "/assets/characters/food/food-egg.svg",
    "food-yogurt": "/assets/characters/food/food-yogurt.svg",
    "food-toast": "/assets/characters/food/food-toast.svg",
    "food-chicken": "/assets/characters/food/food-chicken.svg",
    "food-rice": "/assets/characters/food/food-rice.svg",
    "food-broccoli": "/assets/characters/food/food-broccoli.svg",
    "food-banana": "/assets/characters/food/food-banana.svg",
    "food-milk": "/assets/characters/food/food-milk.svg",
    "food-almond": "/assets/characters/food/food-almond.svg",
    "food-salmon": "/assets/characters/food/food-salmon.svg",
    "food-sweet-potato": "/assets/characters/food/food-sweet-potato.svg",
    "food-spinach": "/assets/characters/food/food-spinach.svg"
  },
  "motionOrigins": {
    "sq-legs": "50% 84.375%",
    "sq-upper": "50% 50%",
    "row-arm": "50% 50%",
    "br-hip": "50.8% 82%",
    "walk-bean": "50% 78.125%"
  }
};
