// Generated by scripts/build-miniprogram-assets.ts — do not edit.
module.exports = {
  "target": [
    {
      "value": "fat_loss",
      "label": "减脂"
    },
    {
      "value": "muscle_gain",
      "label": "增肌"
    },
    {
      "value": "general_fitness",
      "label": "保持体能"
    }
  ],
  "ageBand": [
    {
      "value": "under_18",
      "label": "未满 18 岁"
    },
    {
      "value": "18_24",
      "label": "18–24 岁"
    },
    {
      "value": "25_34",
      "label": "25–34 岁"
    },
    {
      "value": "35_44",
      "label": "35–44 岁"
    },
    {
      "value": "45_54",
      "label": "45–54 岁"
    },
    {
      "value": "55_plus",
      "label": "55 岁以上"
    }
  ],
  "trainingExperience": [
    {
      "value": "beginner",
      "label": "刚开始练"
    },
    {
      "value": "intermediate",
      "label": "练过一段时间"
    },
    {
      "value": "advanced",
      "label": "经常训练"
    }
  ],
  "equipment": [
    {
      "value": "dumbbell",
      "label": "哑铃"
    },
    {
      "value": "band",
      "label": "弹力带"
    },
    {
      "value": "kettlebell",
      "label": "壶铃"
    },
    {
      "value": "bench",
      "label": "平凳"
    },
    {
      "value": "gym",
      "label": "去健身房"
    }
  ],
  "injury": [
    {
      "value": "knee_discomfort",
      "label": "膝盖"
    },
    {
      "value": "back_discomfort",
      "label": "腰背"
    },
    {
      "value": "shoulder_discomfort",
      "label": "肩膀"
    },
    {
      "value": "wrist_discomfort",
      "label": "手腕"
    },
    {
      "value": "ankle_discomfort",
      "label": "脚踝"
    }
  ],
  "allergy": [
    {
      "value": "egg",
      "label": "鸡蛋"
    },
    {
      "value": "milk",
      "label": "牛奶"
    },
    {
      "value": "wheat",
      "label": "小麦"
    },
    {
      "value": "fish",
      "label": "鱼"
    },
    {
      "value": "shellfish",
      "label": "虾蟹贝"
    },
    {
      "value": "soy",
      "label": "大豆"
    },
    {
      "value": "peanut",
      "label": "花生"
    },
    {
      "value": "tree_nut",
      "label": "坚果"
    }
  ],
  "risk": [
    {
      "value": "pregnancy",
      "label": "怀孕或备孕"
    },
    {
      "value": "acute_pain",
      "label": "最近有明显疼痛或受伤"
    },
    {
      "value": "chronic_disease",
      "label": "有慢性病在治疗"
    },
    {
      "value": "eating_disorder",
      "label": "有过进食障碍"
    }
  ]
};
