// Generates the mini-program's character images, icon images, numeral font
// stylesheet and lookup module from packages/illustrations. Output is
// committed (DevTools uploads the folder as-is); `--check` fails if it drifted.
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  exerciseCharacters,
  exerciseKindByCatalogId,
  foodCharacters,
  icons,
  layerSvgDocument,
  motionOrigins,
  navIcons,
  standaloneSvg,
  type CharacterKind,
} from "../packages/illustrations/src/index";
import { buildPreviewDataset } from "./lib/preview-plan";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const app = path.join(root, "apps", "miniprogram");
const TRAIN = "#D85C28";
const INK_3 = "#A79C8B";
const INK = "#2E2A24";
const DIET = "#4F9D6E";
const iconColor: Record<string, string> = { arrow: TRAIN, sun: DIET };

const header = "// Generated by scripts/build-miniprogram-assets.ts — do not edit.\n";

export async function renderAssets(): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  const exercise: Record<string, Array<{ src: string; motion: string | null }>> = {};
  for (const kind of Object.keys(exerciseCharacters) as CharacterKind[]) {
    exerciseCharacters[kind].layers.forEach((layer, index) => {
      files.set(`assets/characters/exercise/${kind}-${index}.svg`, layerSvgDocument(kind, index));
    });
  }
  for (const [catalogId, kind] of Object.entries(exerciseKindByCatalogId)) {
    exercise[catalogId] = exerciseCharacters[kind].layers.map((layer, index) => ({ src: `/assets/characters/exercise/${kind}-${index}.svg`, motion: layer.motion }));
  }
  const food: Record<string, string> = {};
  for (const [catalogId, markup] of Object.entries(foodCharacters)) {
    files.set(`assets/characters/food/${catalogId}.svg`, standaloneSvg(markup));
    food[catalogId] = `/assets/characters/food/${catalogId}.svg`;
  }
  for (const [name, markup] of Object.entries(icons)) {
    files.set(`assets/icons/${name}.svg`, standaloneSvg(markup.replaceAll("currentColor", iconColor[name] ?? INK)));
  }
  for (const [name, markup] of Object.entries(navIcons)) {
    files.set(`assets/icons/nav-${name}-on.svg`, standaloneSvg(markup.replaceAll("currentColor", TRAIN)));
    files.set(`assets/icons/nav-${name}-off.svg`, standaloneSvg(markup.replaceAll("currentColor", INK_3)));
  }
  files.set("utils/characters.js", `${header}module.exports = ${JSON.stringify({ exercise, food, motionOrigins }, null, 2)};\n`);
  files.set("utils/preview-data.js", `${header}// Demo client and plan produced by the real API seam (scripts/lib/preview-plan.ts); used only without a real AppID.\nmodule.exports = ${JSON.stringify(await buildPreviewDataset())};\n`);
  const font = await readFile(path.join(root, "design", "fonts", "fredoka-600-numerals.woff"));
  files.set("styles/numerals.wxss", `/* Generated by scripts/build-miniprogram-assets.ts — Fredoka (SIL OFL 1.1), numerals subset. */\n@font-face { font-family: "Fredoka"; font-weight: 600; font-style: normal; src: url("data:font/woff;base64,${font.toString("base64")}") format("woff"); }\n`);
  return files;
}

async function listGenerated(): Promise<string[]> {
  const found: string[] = [];
  for (const dir of ["assets/characters/exercise", "assets/characters/food", "assets/icons"]) {
    try { for (const name of await readdir(path.join(app, dir))) found.push(`${dir}/${name}`); } catch { /* missing directory */ }
  }
  return found;
}

async function main() {
  const check = process.argv.includes("--check");
  const files = await renderAssets();
  const drift: string[] = [];
  for (const [relative, content] of files) {
    const target = path.join(app, relative);
    if (check) {
      const current = await readFile(target, "utf8").catch(() => null);
      if (current !== content) drift.push(relative);
    } else {
      await mkdir(path.dirname(target), { recursive: true });
      await writeFile(target, content);
    }
  }
  const stale = (await listGenerated()).filter((relative) => !files.has(relative));
  if (check && (drift.length || stale.length)) {
    console.error(`mini-program assets out of date: ${[...drift, ...stale.map((item) => `${item} (stale)`)].join(", ")}\nrun: npx tsx scripts/build-miniprogram-assets.ts`);
    process.exit(1);
  }
  if (!check) console.log(`wrote ${files.size} mini-program assets${stale.length ? `; remove stale: ${stale.join(", ")}` : ""}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) await main();
